spring.application.name=${SPRING_APP_NAME:ewallet}

logging.pattern.console=${LOGPATTERN_CONSOLE:%clr(%d{HH:mm:ss}){green} %clr(%-5level){blue} %clr([%thread]){red} %clr(%logger{36}){yellow} - %msg%n}

logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}

#spring.config.import=application_prod.properties
#spring.profiles.active=prod

spring.datasource.url=jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3308}/${DATABASE_NAME:ewallet}

spring.datasource.username=${DATABASE_USERNAME:root}

spring.datasource.password=${DATABASE_PASSWORD:12345678}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=${JPA_SHOW_SQL:true}

spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}

#server.servlet.session.timeout=${SERVER_SESSION_TIMEOUT:20m}

spring.security.user.name=${SECURITY_USER_NAME:fii}

spring.security.user.password=${SECURITY_USER_PASSWORD:12345678}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sophannarith38@gmail.com
spring.mail.password=mhujqlbjnoozcltm

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=mX9vQ2kL7pR8sT1zW6bN4cD9fH3jK5mA7yU0xZ2qV8nB6eR1tS9hJ4kL3pW8cF2
jwt.expiration=3600000

aws.access-key=AKIA6ODU3JKYUCCVQ36U
aws.secret-key=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
aws.region=ap-southeast-2
aws.bucket-name=ewallet-demo-bucket-992382503601-ap-southeast-2-an

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


