spring.application.name=${SPRING_APP_NAME:ewallet}

app.base-url=${APP_BASE_URL:http://localhost:8080}

app.bootstrap.enabled=${APP_BOOTSTRAP_ENABLED:true}
app.bootstrap.admin.email=${APP_BOOTSTRAP_ADMIN_EMAIL:admin@ewallet.com}
app.bootstrap.admin.password=${APP_BOOTSTRAP_ADMIN_PASSWORD:Admin@12345}
app.bootstrap.admin.balance=${APP_BOOTSTRAP_ADMIN_BALANCE:99999999}

logging.pattern.console=${LOGPATTERN_CONSOLE:%clr(%d{HH:mm:ss}){green} %clr(%-5level){blue} %clr([%thread]){red} %clr(%logger{36}){yellow} - %msg%n}

logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}

#spring.config.import=application_prod.properties
#spring.profiles.active=prod

spring.datasource.url=jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3308}/${DATABASE_NAME:ewallet}

spring.datasource.username=${DATABASE_USERNAME:root}

spring.datasource.password=${DATABASE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=${JPA_SHOW_SQL:true}

spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}

#server.servlet.session.timeout=${SERVER_SESSION_TIMEOUT:20m}

spring.security.user.name=${SECURITY_USER_NAME:fii}

spring.security.user.password=${SECURITY_USER_PASSWORD:}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=${JWT_SECRET:change-me}
jwt.expiration=3600000

aws.access-key=${AWS_ACCESS_KEY:}
aws.secret-key=${AWS_SECRET_KEY:}
aws.region=${AWS_REGION:ap-southeast-2}
aws.bucket-name=${AWS_BUCKET_NAME:}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


